"""add column to cheeses

Revision ID: de93667665ef
Revises: 4ff40efad1fc
Create Date: 2024-02-26 14:48:41.227295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de93667665ef'
down_revision = '4ff40efad1fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheeses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_cheeses_producer_id_producers'), 'producers', ['producer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cheeses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cheeses_producer_id_producers'), type_='foreignkey')
        batch_op.drop_column('producer_id')

    # ### end Alembic commands ###
